/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/environment/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description Configuration presence only; no network call or credential disclosure.
         */
        get: operations["sources_api_v1_environment_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environment/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Context
         * @description Independent environmental context; never corroborates the fictional demo incident.
         */
        get: operations["context_api_v1_environment_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environment/satellite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Satellite Context
         * @description Independent bounded satellite lookup; lets the UI show ground data without waiting.
         */
        get: operations["satellite_context_api_v1_environment_satellite_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/citizen-reports/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_citizen_reports_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/citizen-reports/{report_id}/corroborate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Corroborate */
        post: operations["corroborate_api_v1_citizen_reports__report_id__corroborate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Detail */
        get: operations["incident_detail_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_v1_incidents__incident_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share */
        post: operations["share_api_v1_incidents__incident_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirQualityIndex */
        AirQualityIndex: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string | null;
            /** Value */
            value: number | null;
            /** Category */
            category: string | null;
            /** Dominant Pollutant */
            dominant_pollutant: string | null;
        };
        /** AirQualityObservation */
        AirQualityObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /** Region Code */
            region_code: string | null;
            /** Indexes */
            indexes: components["schemas"]["AirQualityIndex"][];
            /** Pollutants */
            pollutants: components["schemas"]["PollutantMeasurement"][];
        };
        /**
         * AnalysisStatus
         * @enum {string}
         */
        AnalysisStatus: "interpreted" | "not_configured" | "auth_error" | "model_unavailable" | "quota_limited" | "timeout" | "safety_blocked" | "invalid_response" | "error";
        /** Body_analyze_api_v1_citizen_reports_analyze_post */
        Body_analyze_api_v1_citizen_reports_analyze_post: {
            /**
             * Image
             * @description One JPEG/PNG, maximum 5 MiB and 16 MP
             */
            image: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** CitizenAnalysisResponse */
        CitizenAnalysisResponse: {
            /** Request Id */
            request_id: string;
            status: components["schemas"]["AnalysisStatus"];
            report: components["schemas"]["CitizenReport"];
            analysis: components["schemas"]["GeminiEvidenceAnalysis"] | null;
            evidence: components["schemas"]["CitizenVisualSignal"] | null;
            /** Message */
            message: string;
            /** Latency Ms */
            latency_ms: number;
            /** Structured Report Ttl Seconds */
            structured_report_ttl_seconds: number | null;
        };
        /** CitizenInputError */
        CitizenInputError: {
            /**
             * Status
             * @default invalid_input
             * @constant
             */
            status: "invalid_input";
            /** Message */
            message: string;
        };
        /** CitizenReport */
        CitizenReport: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Description */
            description: string;
            /** Language */
            language: string;
            /** Image Url */
            image_url: string | null;
            /**
             * Source Type
             * @default citizen_report
             * @constant
             */
            source_type: "citizen_report";
        };
        /** CitizenVisualSignal */
        CitizenVisualSignal: {
            /** Id */
            id: string;
            signal_type: components["schemas"]["SignalType"];
            /** Source */
            source: string;
            status: components["schemas"]["EvidenceStatus"];
            /** Confidence */
            confidence: null;
            /** Observed At */
            observed_at: null;
            /** Summary */
            summary: string;
            provenance: components["schemas"]["ModelProvenance"];
            /** Raw Reference */
            raw_reference: string | null;
            /** Source Report Id */
            source_report_id: string;
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Interpretation At
             * Format: date-time
             */
            interpretation_at: string;
        };
        /** CorroborationAssessment */
        CorroborationAssessment: {
            /** Id */
            id: string;
            /** Report Id */
            report_id: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            event_type: components["schemas"]["EventType"];
            event_family: components["schemas"]["EventFamily"];
            support_level: components["schemas"]["SupportLevel"];
            recommended_next_step: components["schemas"]["NextStep"];
            /**
             * Temporal Basis
             * @default submission_time_proxy
             * @constant
             */
            temporal_basis: "submission_time_proxy";
            /**
             * Submission Time
             * Format: date-time
             */
            submission_time: string;
            /** Rules */
            rules: components["schemas"]["CorroborationRuleResult"][];
            /** Aggregation Explanation */
            aggregation_explanation: string;
            /** Contributing Rule Ids */
            contributing_rule_ids: string[];
            /** Source Summary */
            source_summary: components["schemas"]["SourceSummary"][];
            environmental_context: components["schemas"]["EnvironmentalContext"];
            /** Limitations */
            limitations: string[];
            provenance: components["schemas"]["Provenance"];
            /**
             * Policy Version
             * @default corroboration_v1
             * @constant
             */
            policy_version: "corroboration_v1";
        };
        /** CorroborationRuleResult */
        CorroborationRuleResult: {
            /** Rule Id */
            rule_id: string;
            /** Source */
            source: string;
            verdict: components["schemas"]["Verdict"];
            /** Summary */
            summary: string;
            /** Inputs Used */
            inputs_used: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Evidence References */
            evidence_references: components["schemas"]["EvidenceReference"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** EnvironmentalContext */
        EnvironmentalContext: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Requested Reference Time */
            requested_reference_time: string | null;
            /**
             * Time Mode
             * @default current
             * @constant
             */
            time_mode: "current";
            /**
             * Temporal Note
             * @default AQ, weather and FIRMS query current conditions. Satellite uses its explicit search window.
             */
            temporal_note: string;
            satellite: components["schemas"]["SatelliteAtmosphericContext"] | null;
            air_quality: components["schemas"]["AirQualityObservation"] | null;
            weather: components["schemas"]["MeteorologicalObservation"] | null;
            /** Fires */
            fires: components["schemas"]["FireObservation"][] | null;
            /** Fire Dataset */
            fire_dataset: string;
            /** Fire Search Radius Km */
            fire_search_radius_km: number;
            /** Fire Window Days */
            fire_window_days: number;
            source_statuses: components["schemas"]["EnvironmentalSourceStatuses"];
            /**
             * Incident Relationship
             * @default independent_context_not_demo_corroboration
             * @constant
             */
            incident_relationship: "independent_context_not_demo_corroboration";
        };
        /** EnvironmentalProvenance */
        EnvironmentalProvenance: {
            /** Source Id */
            source_id: string;
            /** Method */
            method: string;
            /**
             * Is Demo
             * @default false
             * @constant
             */
            is_demo: false;
            /** Note */
            note: string;
            /** Documentation Url */
            documentation_url: string;
        };
        /** EnvironmentalSourceStatus */
        EnvironmentalSourceStatus: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            status: components["schemas"]["SourceState"];
            /** Message */
            message: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Latency Ms */
            latency_ms: number;
        };
        /** EnvironmentalSourceStatuses */
        EnvironmentalSourceStatuses: {
            air_quality: components["schemas"]["EnvironmentalSourceStatus"];
            weather: components["schemas"]["EnvironmentalSourceStatus"];
            fires: components["schemas"]["EnvironmentalSourceStatus"];
        };
        /** EnvironmentalSources */
        EnvironmentalSources: {
            air_quality: components["schemas"]["ProviderConfiguration"];
            weather: components["schemas"]["ProviderConfiguration"];
            fires: components["schemas"]["ProviderConfiguration"];
        };
        /**
         * EventFamily
         * @enum {string}
         */
        EventFamily: "COMBUSTION" | "DUST" | "ATMOSPHERIC_HAZE" | "TRAFFIC" | "NONE_OR_UNCERTAIN";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "open_burning" | "industrial_smoke" | "construction_dust" | "road_dust" | "vehicular_emissions" | "fire_or_combustion" | "haze_or_smog" | "no_visible_pollution" | "uncertain" | "other";
        /** EvidenceReference */
        EvidenceReference: {
            /** Source Id */
            source_id: string;
            /** Observed At */
            observed_at: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Age Seconds */
            age_seconds: number | null;
            /** Submission Offset Seconds */
            submission_offset_seconds: number | null;
            /** Provenance */
            provenance: components["schemas"]["ModelProvenance"] | components["schemas"]["EnvironmentalProvenance"] | components["schemas"]["Provenance"];
        };
        /** EvidenceSignal */
        EvidenceSignal: {
            /** Id */
            id: string;
            signal_type: components["schemas"]["SignalType"];
            /** Source */
            source: string;
            status: components["schemas"]["EvidenceStatus"];
            /** Confidence */
            confidence: number | null;
            /** Observed At */
            observed_at: string | null;
            /** Summary */
            summary: string;
            provenance: components["schemas"]["Provenance"];
            /** Raw Reference */
            raw_reference: string | null;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "interpreted" | "supported" | "partial" | "unavailable" | "conflicting";
        /** FireObservation */
        FireObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /** Source Id */
            source_id: string;
            /**
             * Description
             * @default Nearby active-fire detection
             * @constant
             */
            description: "Nearby active-fire detection";
            /** Confidence */
            confidence: ("l" | "n" | "h") | null;
            /** Satellite */
            satellite: string | null;
            /** Instrument */
            instrument: string | null;
            brightness: components["schemas"]["Measurement"] | null;
            fire_radiative_power: components["schemas"]["Measurement"] | null;
            /** Distance From Query Km */
            distance_from_query_km: number;
        };
        /** ForecastRisk */
        ForecastRisk: {
            /** Horizon Hours */
            horizon_hours: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Spike Probability */
            spike_probability: number;
            /** Predicted Direction */
            predicted_direction: string | null;
            /** Summary */
            summary: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            provenance: components["schemas"]["Provenance"];
        };
        /** GeminiEvidenceAnalysis */
        GeminiEvidenceAnalysis: {
            event_type: components["schemas"]["EventType"];
            event_type_confidence: components["schemas"]["VisualConfidence"];
            /** Visible Smoke */
            visible_smoke: boolean | null;
            /** Visible Flames */
            visible_flames: boolean | null;
            /** Visible Dust */
            visible_dust: boolean | null;
            /** Industrial Context */
            industrial_context: boolean | null;
            /** Construction Context */
            construction_context: boolean | null;
            /** Waste Burning Context */
            waste_burning_context: boolean | null;
            /** Vegetation Burning Context */
            vegetation_burning_context: boolean | null;
            /** Traffic Context */
            traffic_context: boolean | null;
            /**
             * Scene Type
             * @enum {string}
             */
            scene_type: "outdoor" | "indoor" | "unclear";
            /**
             * Apparent Scale
             * @enum {string}
             */
            apparent_scale: "localized" | "widespread_in_frame" | "unclear";
            /** Visual Observations */
            visual_observations: components["schemas"]["VisualObservation"][];
            /** Uncertainty Reasons */
            uncertainty_reasons: components["schemas"]["VisualUncertainty"][];
            /**
             * Insufficient Evidence
             * @description True only when visual ambiguity prevents choosing an event category. False for a clear no_visible_pollution scene. True requires uncertain with low confidence.
             */
            insufficient_evidence: boolean;
            /** Source Report Id */
            source_report_id: string;
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
            provenance: components["schemas"]["ModelProvenance"];
            /**
             * Safety Note
             * @default AI interpretation — requires environmental corroboration. Visual evidence only; an image cannot establish pollutant concentration, source causality or a violation.
             * @constant
             */
            safety_note: "AI interpretation — requires environmental corroboration. Visual evidence only; an image cannot establish pollutant concentration, source causality or a violation.";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentAction */
        IncidentAction: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "acknowledge" | "share";
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "simulated";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            target_jurisdiction: components["schemas"]["Jurisdiction"] | null;
            /** Description */
            description: string;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "open" | "acknowledged";
        JsonValue: unknown;
        /** Jurisdiction */
        Jurisdiction: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Authority Type */
            authority_type: string;
        };
        /** Measurement */
        Measurement: {
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** MeteorologicalObservation */
        MeteorologicalObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            temperature: components["schemas"]["Measurement"] | null;
            /** Relative Humidity Percent */
            relative_humidity_percent: number | null;
            wind_speed: components["schemas"]["Measurement"] | null;
            /** Wind From Degrees */
            wind_from_degrees: number | null;
            /** Wind Cardinal */
            wind_cardinal: string | null;
            sea_level_pressure: components["schemas"]["Measurement"] | null;
            /** Precipitation Probability Percent */
            precipitation_probability_percent: number | null;
            precipitation_qpf: components["schemas"]["Measurement"] | null;
            /** Cloud Cover Percent */
            cloud_cover_percent: number | null;
        };
        /** ModelProvenance */
        ModelProvenance: {
            /** Source Id */
            source_id: string;
            /** Method */
            method: string;
            /** Is Demo */
            is_demo: boolean;
            /** Note */
            note: string;
            /** Model */
            model: string;
            /** Model Version */
            model_version: string | null;
            /**
             * Prompt Version
             * @default citizen_evidence_v1
             * @constant
             */
            prompt_version: "citizen_evidence_v1";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Source Report Id */
            source_report_id: string;
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Author
             * @default model
             * @constant
             */
            author: "model";
            /**
             * Confidence Basis
             * @default model_estimated_ordinal_not_calibrated
             * @constant
             */
            confidence_basis: "model_estimated_ordinal_not_calibrated";
        };
        /**
         * NextStep
         * @enum {string}
         */
        NextStep: "FIELD_VERIFICATION" | "MONITOR" | "REVIEW" | "NO_ACTION_FROM_CURRENT_EVIDENCE";
        /** PollutantMeasurement */
        PollutantMeasurement: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Full Name */
            full_name: string | null;
            concentration: components["schemas"]["Measurement"] | null;
        };
        /** PollutionIncident */
        PollutionIncident: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Event Type
             * @constant
             */
            event_type: "probable_open_burning";
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["RiskLevel"];
            /** Confidence */
            confidence: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSignal"][];
            /** Citizen Reports */
            citizen_reports: components["schemas"]["CitizenReport"][];
            forecast: components["schemas"]["ForecastRisk"];
            /** Recommended Action */
            recommended_action: string;
            /** Affected Jurisdictions */
            affected_jurisdictions: components["schemas"]["Jurisdiction"][];
            /** Actions */
            actions: components["schemas"]["IncidentAction"][];
            /** Model Version */
            model_version: string | null;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Field Verification Required
             * @default true
             */
            field_verification_required: boolean;
            provenance: components["schemas"]["Provenance"];
        };
        /** Provenance */
        Provenance: {
            /** Source Id */
            source_id: string;
            /** Method */
            method: string;
            /** Is Demo */
            is_demo: boolean;
            /** Note */
            note: string;
        };
        /** ProviderConfiguration */
        ProviderConfiguration: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            /**
             * Configuration State
             * @enum {string}
             */
            configuration_state: "configured" | "not_configured";
        };
        /** ReportUnavailable */
        ReportUnavailable: {
            /**
             * Detail
             * @default Report expired or unavailable. Analyze the image again to corroborate it.
             */
            detail: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "moderate" | "high";
        /** SatelliteAtmosphericContext */
        SatelliteAtmosphericContext: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Query Latitude */
            query_latitude: number;
            /** Query Longitude */
            query_longitude: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            search_window: components["schemas"]["SatelliteSearchWindow"];
            /** Retrieval Radius Km */
            retrieval_radius_km: number;
            /** Grid Scale M */
            grid_scale_m: number;
            /** Products */
            products: components["schemas"]["SatelliteProductResult"][];
            provider_status: components["schemas"]["EnvironmentalSourceStatus"];
            /**
             * Availability
             * @enum {string}
             */
            availability: "complete" | "partial" | "none";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /**
             * Temporal Note
             * @default Latest usable observation per product; acquisition times may differ. Not real-time.
             */
            temporal_note: string;
            /**
             * Measurement Note
             * @default Satellite atmospheric columns are regional context and are not equivalent to ground-level pollutant concentrations.
             */
            measurement_note: string;
        };
        /** SatelliteObservation */
        SatelliteObservation: {
            /**
             * Product
             * @enum {string}
             */
            product: "no2" | "co" | "aerosol_index";
            /** Value */
            value: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mol/m²" | "dimensionless";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Age Seconds */
            age_seconds: number;
            /** Collection */
            collection: string;
            /** Band */
            band: string;
            /** Image Id */
            image_id: string;
            /** Source Product Id */
            source_product_id: string | null;
            /** Grid Scale M */
            grid_scale_m: number;
            /** Native Footprint */
            native_footprint: string | null;
            /** Retrieval Radius Km */
            retrieval_radius_km: number;
            /**
             * Statistic
             * @default mean
             * @constant
             */
            statistic: "mean";
            quality: components["schemas"]["SatelliteQuality"];
            provenance: components["schemas"]["EnvironmentalProvenance"];
        };
        /** SatelliteProductResult */
        SatelliteProductResult: {
            /**
             * Product
             * @enum {string}
             */
            product: "no2" | "co" | "aerosol_index";
            status: components["schemas"]["SourceState"];
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "no_scene" | "quality_filtered" | "no_usable_pixels" | "not_configured" | "authentication_error" | "configuration_error" | "provider_error" | "timeout" | "busy";
            /** Message */
            message: string;
            /** Collection */
            collection: string;
            /** Band */
            band: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mol/m²" | "dimensionless";
            observation: components["schemas"]["SatelliteObservation"] | null;
            /** Scene Count */
            scene_count: number | null;
            /** Quality Scene Count */
            quality_scene_count: number | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /** SatelliteQuality */
        SatelliteQuality: {
            /**
             * Status
             * @default usable
             * @constant
             */
            status: "usable";
            /** Catalog Qa Rule */
            catalog_qa_rule: string;
            /**
             * Scene Quality
             * @enum {string}
             */
            scene_quality: "Nominal" | "NOMINAL";
            /**
             * Processing Status
             * @enum {string}
             */
            processing_status: "Nominal" | "NRTI-processing product";
            /** Valid Grid Cells */
            valid_grid_cells: number;
            /** Applied Filters */
            applied_filters: string[];
            /**
             * Note
             * @default L3 ingestion QA is upstream; original per-pixel QA is not exposed. Not a confidence score.
             */
            note: string;
        };
        /** SatelliteSearchWindow */
        SatelliteSearchWindow: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Lookback Hours */
            lookback_hours: number;
            /**
             * End Mode
             * @enum {string}
             */
            end_mode: "explicit" | "current_hour";
        };
        /** ShareRequest */
        ShareRequest: {
            /** Target Jurisdiction Id */
            target_jurisdiction_id: string;
        };
        /** ShareResponse */
        ShareResponse: {
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
            action: components["schemas"]["IncidentAction"];
            incident: components["schemas"]["PollutionIncident"];
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "citizen_report" | "air_quality" | "fire" | "wind" | "satellite";
        /**
         * SourceState
         * @enum {string}
         */
        SourceState: "live" | "cached" | "unavailable" | "not_configured" | "error";
        /** SourceSummary */
        SourceSummary: {
            /** Source */
            source: string;
            status: components["schemas"]["SourceState"];
            verdict: components["schemas"]["Verdict"];
            /** Message */
            message: string;
        };
        /**
         * SupportLevel
         * @enum {string}
         */
        SupportLevel: "STRONG" | "MODERATE" | "WEAK" | "INSUFFICIENT" | "CONFLICTING";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "SUPPORTS" | "WEAKLY_SUPPORTS" | "NEUTRAL" | "CONTRADICTS" | "UNAVAILABLE" | "STALE" | "NOT_APPLICABLE";
        /**
         * VisualConfidence
         * @enum {string}
         */
        VisualConfidence: "low" | "medium" | "high";
        /**
         * VisualObservation
         * @enum {string}
         */
        VisualObservation: "Gray plume or cloud-like feature visible." | "Dark plume-like feature visible." | "Flame-like features visible." | "Tan dust-like cloud visible." | "Reduced visibility or diffuse haze visible." | "Cloud or fog-like features visible." | "Open ground visible." | "Buildings or structures visible." | "Industrial-looking structures visible." | "Construction equipment or exposed earth visible." | "Vehicles or roadway visible." | "Vegetation visible." | "Pile of material visible; composition unknown." | "No clear smoke, flame or dust-like feature visible." | "Indoor objects visible." | "Low light limits visible detail." | "Blur or low resolution limits visible detail.";
        /**
         * VisualUncertainty
         * @enum {string}
         */
        VisualUncertainty: "Image alone cannot establish source or pollutant type." | "Material composition cannot be established visually." | "Smoke, dust, cloud and fog can look similar." | "Distant or obscured features limit interpretation." | "Lighting, blur or resolution limits interpretation." | "Citizen description is unverified context, not visual evidence." | "Image alone cannot establish pollutant concentration or air quality." | "No clear pollution-related event can be inferred from this image." | "The image appears illustrative or synthetic; real conditions cannot be established.";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sources_api_v1_environment_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentalSources"];
                };
            };
        };
    };
    context_api_v1_environment_context_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                include_satellite?: boolean;
                lookback_hours?: number | null;
                /** @description Optional reference time. Ground providers still query current conditions. Satellite uses this as its window end. Include a timezone. */
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentalContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satellite_context_api_v1_environment_satellite_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                at?: string | null;
                lookback_hours?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatelliteAtmosphericContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_citizen_reports_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_v1_citizen_reports_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitizenAnalysisResponse"];
                };
            };
            /** @description Content Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitizenInputError"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CitizenInputError"];
                };
            };
        };
    };
    corroborate_api_v1_citizen_reports__report_id__corroborate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorroborationAssessment"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportUnavailable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"][];
                };
            };
        };
    };
    incident_detail_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_v1_incidents__incident_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_api_v1_incidents__incident_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
