/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/environment/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sources
         * @description Configuration presence only; no network call or credential disclosure.
         */
        get: operations["sources_api_v1_environment_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environment/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Context
         * @description Independent environmental context; never corroborates the fictional demo incident.
         */
        get: operations["context_api_v1_environment_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environment/satellite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Satellite Context
         * @description Independent bounded satellite lookup; lets the UI show ground data without waiting.
         */
        get: operations["satellite_context_api_v1_environment_satellite_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident Detail */
        get: operations["incident_detail_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge */
        post: operations["acknowledge_api_v1_incidents__incident_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share */
        post: operations["share_api_v1_incidents__incident_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AirQualityIndex */
        AirQualityIndex: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string | null;
            /** Value */
            value: number | null;
            /** Category */
            category: string | null;
            /** Dominant Pollutant */
            dominant_pollutant: string | null;
        };
        /** AirQualityObservation */
        AirQualityObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /** Region Code */
            region_code: string | null;
            /** Indexes */
            indexes: components["schemas"]["AirQualityIndex"][];
            /** Pollutants */
            pollutants: components["schemas"]["PollutantMeasurement"][];
        };
        /** CitizenReport */
        CitizenReport: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Description */
            description: string;
            /** Language */
            language: string;
            /** Image Url */
            image_url: string | null;
            /**
             * Source Type
             * @default citizen_report
             * @constant
             */
            source_type: "citizen_report";
        };
        /** EnvironmentalContext */
        EnvironmentalContext: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Requested Reference Time */
            requested_reference_time: string | null;
            /**
             * Time Mode
             * @default current
             * @constant
             */
            time_mode: "current";
            /**
             * Temporal Note
             * @default AQ, weather and FIRMS query current conditions. Satellite uses its explicit search window.
             */
            temporal_note: string;
            satellite: components["schemas"]["SatelliteAtmosphericContext"] | null;
            air_quality: components["schemas"]["AirQualityObservation"] | null;
            weather: components["schemas"]["MeteorologicalObservation"] | null;
            /** Fires */
            fires: components["schemas"]["FireObservation"][] | null;
            /** Fire Dataset */
            fire_dataset: string;
            /** Fire Search Radius Km */
            fire_search_radius_km: number;
            /** Fire Window Days */
            fire_window_days: number;
            source_statuses: components["schemas"]["EnvironmentalSourceStatuses"];
            /**
             * Incident Relationship
             * @default independent_context_not_demo_corroboration
             * @constant
             */
            incident_relationship: "independent_context_not_demo_corroboration";
        };
        /** EnvironmentalProvenance */
        EnvironmentalProvenance: {
            /** Source Id */
            source_id: string;
            /** Method */
            method: string;
            /**
             * Is Demo
             * @default false
             * @constant
             */
            is_demo: false;
            /** Note */
            note: string;
            /** Documentation Url */
            documentation_url: string;
        };
        /** EnvironmentalSourceStatus */
        EnvironmentalSourceStatus: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            status: components["schemas"]["SourceState"];
            /** Message */
            message: string;
            /** Retrieved At */
            retrieved_at: string | null;
            /** Latency Ms */
            latency_ms: number;
        };
        /** EnvironmentalSourceStatuses */
        EnvironmentalSourceStatuses: {
            air_quality: components["schemas"]["EnvironmentalSourceStatus"];
            weather: components["schemas"]["EnvironmentalSourceStatus"];
            fires: components["schemas"]["EnvironmentalSourceStatus"];
        };
        /** EnvironmentalSources */
        EnvironmentalSources: {
            air_quality: components["schemas"]["ProviderConfiguration"];
            weather: components["schemas"]["ProviderConfiguration"];
            fires: components["schemas"]["ProviderConfiguration"];
        };
        /** EvidenceSignal */
        EvidenceSignal: {
            /** Id */
            id: string;
            signal_type: components["schemas"]["SignalType"];
            /** Source */
            source: string;
            status: components["schemas"]["EvidenceStatus"];
            /** Confidence */
            confidence: number | null;
            /** Observed At */
            observed_at: string | null;
            /** Summary */
            summary: string;
            provenance: components["schemas"]["Provenance"];
            /** Raw Reference */
            raw_reference: string | null;
        };
        /**
         * EvidenceStatus
         * @enum {string}
         */
        EvidenceStatus: "supported" | "partial" | "unavailable" | "conflicting";
        /** FireObservation */
        FireObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /** Source Id */
            source_id: string;
            /**
             * Description
             * @default Nearby active-fire detection
             * @constant
             */
            description: "Nearby active-fire detection";
            /** Confidence */
            confidence: ("l" | "n" | "h") | null;
            /** Satellite */
            satellite: string | null;
            /** Instrument */
            instrument: string | null;
            brightness: components["schemas"]["Measurement"] | null;
            fire_radiative_power: components["schemas"]["Measurement"] | null;
            /** Distance From Query Km */
            distance_from_query_km: number;
        };
        /** ForecastRisk */
        ForecastRisk: {
            /** Horizon Hours */
            horizon_hours: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Spike Probability */
            spike_probability: number;
            /** Predicted Direction */
            predicted_direction: string | null;
            /** Summary */
            summary: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            provenance: components["schemas"]["Provenance"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentAction */
        IncidentAction: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "acknowledge" | "share";
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "simulated";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            target_jurisdiction: components["schemas"]["Jurisdiction"] | null;
            /** Description */
            description: string;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "open" | "acknowledged";
        /** Jurisdiction */
        Jurisdiction: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Authority Type */
            authority_type: string;
        };
        /** Measurement */
        Measurement: {
            /** Value */
            value: number;
            /** Unit */
            unit: string;
        };
        /** MeteorologicalObservation */
        MeteorologicalObservation: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /**
             * Status
             * @default live
             * @enum {string}
             */
            status: "live" | "cached";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            temperature: components["schemas"]["Measurement"] | null;
            /** Relative Humidity Percent */
            relative_humidity_percent: number | null;
            wind_speed: components["schemas"]["Measurement"] | null;
            /** Wind From Degrees */
            wind_from_degrees: number | null;
            /** Wind Cardinal */
            wind_cardinal: string | null;
            sea_level_pressure: components["schemas"]["Measurement"] | null;
            /** Precipitation Probability Percent */
            precipitation_probability_percent: number | null;
            precipitation_qpf: components["schemas"]["Measurement"] | null;
            /** Cloud Cover Percent */
            cloud_cover_percent: number | null;
        };
        /** PollutantMeasurement */
        PollutantMeasurement: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Full Name */
            full_name: string | null;
            concentration: components["schemas"]["Measurement"] | null;
        };
        /** PollutionIncident */
        PollutionIncident: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Event Type
             * @constant
             */
            event_type: "probable_open_burning";
            status: components["schemas"]["IncidentStatus"];
            severity: components["schemas"]["RiskLevel"];
            /** Confidence */
            confidence: number;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            jurisdiction: components["schemas"]["Jurisdiction"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSignal"][];
            /** Citizen Reports */
            citizen_reports: components["schemas"]["CitizenReport"][];
            forecast: components["schemas"]["ForecastRisk"];
            /** Recommended Action */
            recommended_action: string;
            /** Affected Jurisdictions */
            affected_jurisdictions: components["schemas"]["Jurisdiction"][];
            /** Actions */
            actions: components["schemas"]["IncidentAction"][];
            /** Model Version */
            model_version: string | null;
            /** Is Demo */
            is_demo: boolean;
            /**
             * Field Verification Required
             * @default true
             */
            field_verification_required: boolean;
            provenance: components["schemas"]["Provenance"];
        };
        /** Provenance */
        Provenance: {
            /** Source Id */
            source_id: string;
            /** Method */
            method: string;
            /** Is Demo */
            is_demo: boolean;
            /** Note */
            note: string;
        };
        /** ProviderConfiguration */
        ProviderConfiguration: {
            /** Provider */
            provider: string;
            /** Configured */
            configured: boolean;
            /**
             * Configuration State
             * @enum {string}
             */
            configuration_state: "configured" | "not_configured";
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "low" | "moderate" | "high";
        /** SatelliteAtmosphericContext */
        SatelliteAtmosphericContext: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Query Latitude */
            query_latitude: number;
            /** Query Longitude */
            query_longitude: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            search_window: components["schemas"]["SatelliteSearchWindow"];
            /** Retrieval Radius Km */
            retrieval_radius_km: number;
            /** Grid Scale M */
            grid_scale_m: number;
            /** Products */
            products: components["schemas"]["SatelliteProductResult"][];
            provider_status: components["schemas"]["EnvironmentalSourceStatus"];
            /**
             * Availability
             * @enum {string}
             */
            availability: "complete" | "partial" | "none";
            provenance: components["schemas"]["EnvironmentalProvenance"];
            /**
             * Temporal Note
             * @default Latest usable observation per product; acquisition times may differ. Not real-time.
             */
            temporal_note: string;
            /**
             * Measurement Note
             * @default Satellite atmospheric columns are regional context and are not equivalent to ground-level pollutant concentrations.
             */
            measurement_note: string;
        };
        /** SatelliteObservation */
        SatelliteObservation: {
            /**
             * Product
             * @enum {string}
             */
            product: "no2" | "co" | "aerosol_index";
            /** Value */
            value: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mol/m²" | "dimensionless";
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Age Seconds */
            age_seconds: number;
            /** Collection */
            collection: string;
            /** Band */
            band: string;
            /** Image Id */
            image_id: string;
            /** Source Product Id */
            source_product_id: string | null;
            /** Grid Scale M */
            grid_scale_m: number;
            /** Native Footprint */
            native_footprint: string | null;
            /** Retrieval Radius Km */
            retrieval_radius_km: number;
            /**
             * Statistic
             * @default mean
             * @constant
             */
            statistic: "mean";
            quality: components["schemas"]["SatelliteQuality"];
            provenance: components["schemas"]["EnvironmentalProvenance"];
        };
        /** SatelliteProductResult */
        SatelliteProductResult: {
            /**
             * Product
             * @enum {string}
             */
            product: "no2" | "co" | "aerosol_index";
            status: components["schemas"]["SourceState"];
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "no_scene" | "quality_filtered" | "no_usable_pixels" | "not_configured" | "authentication_error" | "configuration_error" | "provider_error" | "timeout" | "busy";
            /** Message */
            message: string;
            /** Collection */
            collection: string;
            /** Band */
            band: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "mol/m²" | "dimensionless";
            observation: components["schemas"]["SatelliteObservation"] | null;
            /** Scene Count */
            scene_count: number | null;
            /** Quality Scene Count */
            quality_scene_count: number | null;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /** SatelliteQuality */
        SatelliteQuality: {
            /**
             * Status
             * @default usable
             * @constant
             */
            status: "usable";
            /** Catalog Qa Rule */
            catalog_qa_rule: string;
            /**
             * Scene Quality
             * @enum {string}
             */
            scene_quality: "Nominal" | "NOMINAL";
            /**
             * Processing Status
             * @enum {string}
             */
            processing_status: "Nominal" | "NRTI-processing product";
            /** Valid Grid Cells */
            valid_grid_cells: number;
            /** Applied Filters */
            applied_filters: string[];
            /**
             * Note
             * @default L3 ingestion QA is upstream; original per-pixel QA is not exposed. Not a confidence score.
             */
            note: string;
        };
        /** SatelliteSearchWindow */
        SatelliteSearchWindow: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Lookback Hours */
            lookback_hours: number;
            /**
             * End Mode
             * @enum {string}
             */
            end_mode: "explicit" | "current_hour";
        };
        /** ShareRequest */
        ShareRequest: {
            /** Target Jurisdiction Id */
            target_jurisdiction_id: string;
        };
        /** ShareResponse */
        ShareResponse: {
            /**
             * Simulated
             * @default true
             * @constant
             */
            simulated: true;
            action: components["schemas"]["IncidentAction"];
            incident: components["schemas"]["PollutionIncident"];
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "citizen_report" | "air_quality" | "fire" | "wind" | "satellite";
        /**
         * SourceState
         * @enum {string}
         */
        SourceState: "live" | "cached" | "unavailable" | "not_configured" | "error";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sources_api_v1_environment_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentalSources"];
                };
            };
        };
    };
    context_api_v1_environment_context_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                include_satellite?: boolean;
                lookback_hours?: number | null;
                /** @description Optional reference time. Ground providers still query current conditions. Satellite uses this as its window end. Include a timezone. */
                at?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentalContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satellite_context_api_v1_environment_satellite_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                at?: string | null;
                lookback_hours?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SatelliteAtmosphericContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"][];
                };
            };
        };
    };
    incident_detail_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_v1_incidents__incident_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollutionIncident"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_api_v1_incidents__incident_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
